name: compile_and_run
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: docker build
        run: docker build --no-cache -t project .

      - name: docker run
        run: docker run project:latest

