name: compile_and_run
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip' # caching pip dependencies

      - name: install python requirements
        run: pip install -r requirements.txt

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: docker build
        run: docker build --no-cache -t project .

      - name: docker run
        run: docker run project:latest

      - name: upload plots
        uses: actions/upload-artifact@v4
        with:
          name: "plots_$(date +%Y-%m-%d_%H-%M)"
          path: "results/"
